### PR TITLE
fix: use version sort for keyboard help redirection

### LINKED ISSUE #564: bug: keyboard help forwarding is getting wrong version for fv_tlingit
https://help.keyman.com/keyboard/fv_tlingit is forwarding to 
https://help.keyman.com/keyboard/fv_tlingit/9.2/fv_tlingit instead of https://help.keyman.com/keyboard/fv_tlingit/10.0/fv_tlingit. Suspect that it is doing a string rather than numerical comparison (string "10.0" < "9.2" but numeric 10.0 > 9.2).

### PR DESCRIPTION
**Pull request by mcdurdin**
Fixes #564.

### CODE REVIEW

**Review by jahorton — APPROVED** [review]

File: keyboard/redir.php [hunk 1]
```diff
@@ -13,7 +13,7 @@
     $v = "$q/{$_REQUEST['v']}";
     if(!file_exists("$v/$q.php")) {
       unset($v);
-    }
+  }
```
Comment (jahorton) [inline keyboard/redir.php:16]: Maybe undo this removal of indentation?

```suggestion
    }
```
